# Generated by Django 3.2.10 on 2022-07-11 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('total_fees', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Subcenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.center')),
            ],
        ),
        migrations.CreateModel(
            name='Student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=250)),
                ('blood_group', models.CharField(max_length=250)),
                ('mail_id', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('total_fees', models.CharField(max_length=250)),
                ('center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.center')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.course1')),
                ('subcenter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.subcenter')),
            ],
        ),
    ]
