# Generated by Django 3.2.10 on 2022-07-20 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student1',
            old_name='course',
            new_name='course1',
        ),
        migrations.RemoveField(
            model_name='course1',
            name='total_fees',
        ),
        migrations.CreateModel(
            name='Total_fees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('course1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.course1')),
            ],
        ),
        migrations.AlterField(
            model_name='student1',
            name='total_fees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.total_fees'),
        ),
    ]
